#!/bin/bash

# TODO: ensure yq is installed

yq --version 2&1 > /dev/null

if [ $? -ne 0 ]; then
  echo "yq is not installed"
  exit 1
fi

# TODO: ensure helm is installed and at least supported version

helm version 2&1 > /dev/null
if [ $? -ne 0 ]; then
  echo "helm is not installed"
  exit 1
fi