#!/bin/bash

# TODO: ensure yq is installed
# TODO: ensure helm is installed

if [ -z "${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_NAME}" ]; then
  export NAME=$(yq '.name' ./Chart.yaml)
  if [ -z "${NAME}" ]; then
    echo "NAME is not set and Chart.yaml does not contain a name field"
    exit 1
  fi
else
    export NAME="${BUILDKITE_PLUGIN_HELM_OCI_PUBLISHER_NAME}"
fi

echo --- "Using name: ${NAME}"